[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false
# Optionally enable the dev address lookup table
# enable-address-lookup-table = true

[programs.localnet]
nft_staking = "Bjwz8YL6RmzbBPUE1m4gYiTkuNonXGyAH7d5CeJ3yvDj"

[programs.devnet]
nft_staking = "Bjwz8YL6RmzbBPUE1m4gYiTkuNonXGyAH7d5CeJ3yvDj"

[programs.mainnet]
nft_staking = "Bjwz8YL6RmzbBPUE1m4gYiTkuNonXGyAH7d5CeJ3yvDj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 1000000"
build = "anchor build"
deploy = "anchor deploy"
init = "node scripts/init-config.js"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

## Add the Metaplex token metadata program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[workspace]
types = "target/types"
members = ["programs/nft-staking"] 